### ISSUE TITLE
Crash when running as a packaged app with electron-builder on macOS

### ISSUE THREAD

**Issue by jwheare** [sindresorhus/electron-config#1]
```
Uncaught Exception:
TypeError: Expected string, got undefined
    at module.exports.name ([...]IRCCloud.app/Contents/Resources/app.asar/node_modules/env-paths/index.js:49:9)
    at ElectronConfig.Conf ([...]IRCCloud.app/Contents/Resources/app.asar/node_modules/conf/index.js:29:9)
    at ElectronConfig ([...]IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-config/index.js:11:3)
    at setupConfig ([...]IRCCloud.app/Contents/Resources/app.asar/main.js:56:10)
    at Object.<anonymous> ([...]IRCCloud.app/Contents/Resources/app.asar/main.js:60:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

[env-paths](https://github.com/sindresorhus/env-paths/blob/7c516d0755ab2eb9212f4327e047afe036b5bfd2/index.js#L49) expects a String, but [conf](https://github.com/sindresorhus/conf/blob/cffd7b58d6245c0f0c2e8b92d8bc45a4caf52a00/index.js#L29) is passing in an undefined `opts.projectName`, because [electron-config](https://github.com/sindresorhus/electron-config/blob/61e80b5242f147868ffcebc410838efec2bf17e0/index.js#L8) is setting `opts.cwd` directly so it isn't needed.

This fails because the package.json isn't bundled into the asar file when built, so pkg-up finds nothing.

Not sure which package this should be fixed in.

----

Also, a fresh npm install results in this version tree:

```
└─┬ electron-config@0.2.1
  └─┬ conf@0.11.1
    └── env-paths@0.2.0
```

conf depends on env-paths: ^0.2.0 which won't allow 0.3.0

**Comment by sindresorhus** [comment]
Should be fixed in `conf`. It should not call `envPaths` when `cwd` is set. I'll fix tomorrow. Weird that I didn't hit it. I'm using `electron-config` in multiple apps packaged with electron-packager and asar.

**Comment by jwheare** [comment]
Actually, the package.json *is* getting included in the asar, but is still not being recognised.

I originally thought this was because we're using the dual package.json structure [recommended by electron-builder](https://github.com/electron-userland/electron-builder#two-packagejson-structure), since our *outer* package.json has no `name` field set (it serves no purpose), but it's the *inner* package.json that gets bundled, so I'm a bit stumped.

Interesting to note that if there's a package.json *outside* the asar with a name field, the crash doesn't occur, but that's unlikely to happen if the .app gets copied to /Applications

**Comment by jwheare** [comment]
Ah, this could be because both main.js and package.json are in the root of the asar, but it looks like `conf` is [starting the hunt from the parent dir](https://github.com/sindresorhus/conf/blob/cffd7b58d6245c0f0c2e8b92d8bc45a4caf52a00/index.js#L17).

**Comment by jwheare** [comment]
…hmm, unless that's the parent of the conf module, i.e. the node_modules dir.

**Comment by sindresorhus** [comment]
"Parent dir" being the directory of the parent (caller) module, which is your app.

**Comment by jwheare** [comment]
The parent is actually the electron-config module. [Docs say](https://nodejs.org/api/modules.html#modules_module_parent):
```
module.parent

<Object> Module object
The module that first required this one
```

conf isn't required directly from our app.

I added some logging, and here's the parent dir it starts on, and the package.json it finds:

```
~/src/irccloud/desktop/dist/mac/IRCCloud.app/Contents/Resources/app.asar/node_modules/electron-config
~/src/irccloud/desktop/package.json (outer, no name)
```

vs when running in dev mode, unpacked:

```
~/src/irccloud/desktop/app/node_modules/electron-config
~/src/irccloud/desktop/app/node_modules/electron-config/package.json (invalid, but unused anyway)
```

So it looks like it's having trouble traversing the asar tree. It should be finding the inner package.json at:

```
~/src/irccloud/desktop/dist/mac/IRCCloud.app/Contents/Resources/app.asar/package.json
```

Or unpacked at:

```
~/src/irccloud/desktop/app/package.json
```

**Comment by jwheare** [comment]
Perhaps your path-exists isn't taking advantage of electron's patched fs calls that allow asar traversal:

https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md#using-asar-archives

**Comment by sindresorhus** [comment]
There's nothing for `path-exists` to take advantage of. Asar patches all `fs` calls.

**Comment by jwheare** [comment]
You're using fs.access(Sync) in path-exists, which isn't patched, but fs.exists(Sync) is:

https://github.com/electron/electron/blob/a0c5749ac1731afbbb7d042f1717597d6d68ea02/lib/common/asar.js#L342

**Comment by sindresorhus** [comment]
Ah, nice catch! That sounds like an Electron bug (You know what to do). Electron should be patching that `fs.access{Sync,}` too.

**Comment by jwheare** [comment]
Cheers! There's still the issue of the incorrect module.parent, shall I open a separate ticket?

**Comment by sindresorhus** [comment]
@jwheare On `conf`, sure. Not a big issue though, as most would use `conf` directly, and `electron-config` doesn't make use of that feature anyways.
